# Generated by Django 6.0.7 on 2026-08-08 07:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ombor', '0005_narxsozlamasi_ni_hajmnarxiga_kochirish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MahsulotPartiyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelgan_soni', models.PositiveIntegerField()),
                ('tannarx', models.DecimalField(blank=True, decimal_places=2, help_text='Bir dona tannarxi (ixtiyoriy)', max_digits=12, null=True)),
                ('sana', models.DateField()),
                ('izoh', models.CharField(blank=True, max_length=255)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('fura', models.ForeignKey(blank=True, help_text='Qaysi fura bilan kelgani (ixtiyoriy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulot_partiyalari', to='ombor.fura')),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_partiyalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahsulot partiyasi',
                'verbose_name_plural': 'Mahsulot partiyalari',
                'ordering': ['-sana', '-yaratilgan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='PartiyaHarakati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('sotuv', 'Sotuv'), ('ishlatish', 'Ishlatish')], max_length=20)),
                ('soni', models.PositiveIntegerField()),
                ('narx', models.DecimalField(blank=True, decimal_places=2, help_text='Faqat sotuv uchun - bir donaning sotuv narxi', max_digits=12, null=True)),
                ('xaridor', models.CharField(blank=True, max_length=150)),
                ('izoh', models.CharField(blank=True, max_length=255)),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harakatlar', to='sotuv.mahsulotpartiyasi')),
            ],
            options={
                'verbose_name': 'Partiya harakati',
                'verbose_name_plural': 'Partiya harakatlari',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='QoshimchaMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='qoshimcha_mahsulotlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Qo'shimcha mahsulot",
                'verbose_name_plural': "Qo'shimcha mahsulotlar",
                'unique_together': {('menejer', 'nomi')},
            },
        ),
        migrations.AddField(
            model_name='mahsulotpartiyasi',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partiyalar', to='sotuv.qoshimchamahsulot'),
        ),
    ]
