# Generated by Django 6.0.7 on 2026-08-01 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('suv_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dastavka_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('izoh', models.TextField(blank=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='furalar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuraMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hajm', models.CharField(max_length=10)),
                ('miqdor', models.IntegerField()),
                ('fura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='ombor.fura')),
            ],
        ),
    ]
