# Generated by Django 6.0.7 on 2026-08-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fura',
            options={'verbose_name': 'Fura', 'verbose_name_plural': 'Furalar'},
        ),
        migrations.AlterModelOptions(
            name='furamahsulot',
            options={'verbose_name': 'Fura mahsuloti', 'verbose_name_plural': 'Fura mahsulotlari'},
        ),
    ]
