# Generated by Django 6.0.7 on 2026-08-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0002_alter_fura_options_alter_furamahsulot_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NarxSozlamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx_5l', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('narx_10l', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('menejer', models.OneToOneField(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='narx_sozlamasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Narx sozlamasi',
                'verbose_name_plural': 'Narx sozlamalari',
            },
        ),
    ]
