# Generated by Django 6.0.7 on 2026-08-04 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0003_narxsozlamasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HajmNarxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hajm', models.CharField(max_length=20)),
                ('narx', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='hajm_narxlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hajm narxi',
                'verbose_name_plural': 'Hajm narxlari',
                'unique_together': {('menejer', 'hajm')},
            },
        ),
    ]
