# Generated by Django 6.0.7 on 2026-08-09 03:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0005_narxsozlamasi_ni_hajmnarxiga_kochirish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fura',
            name='dastavka_narxi',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Eski maydon - endi qoshimcha_xarajatlar orqali kiritiladi, backward compatibility uchun saqlanmoqda', max_digits=12),
        ),
        migrations.CreateModel(
            name='FuraXarajati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoshimcha_xarajatlar', to='ombor.fura')),
            ],
            options={
                'verbose_name': 'Fura xarajati',
                'verbose_name_plural': 'Fura xarajatlari',
            },
        ),
    ]
