# Generated by Django 6.0.7 on 2026-08-22 19:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0007_dastavka_narxini_furaxarajatiga_kochirish'),
    ]

    operations = [
        migrations.AddField(
            model_name='furamahsulot',
            name='dona_narxi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bir dona suvning kelish narxi', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fura',
            name='suv_narxi',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Eski maydon - butun partiya uchun umumiy suv narxi. Yangi furalarda endi FuraMahsulot.dona_narxi ishlatiladi, backward compatibility uchun saqlanmoqda', max_digits=12),
        ),
    ]
