# Generated by Django 6.0.7 on 2026-08-01 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('izoh', models.CharField(max_length=255)),
                ('sana', models.DateField(default=django.utils.timezone.localdate)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('kim_yozgan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yozgan_xarajatlar', to=settings.AUTH_USER_MODEL)),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='xarajatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
            },
        ),
    ]
