# Generated by Django 6.0.7 on 2026-08-01 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmalar', '0002_alter_buyurtma_options_and_more'),
        ('statistika', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QarzTolovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField(default=django.utils.timezone.localdate)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarz_tolovlari', to='buyurtmalar.buyurtma')),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='qarz_tolovlari', to=settings.AUTH_USER_MODEL)),
                ('qabul_qilgan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabul_qilingan_qarz_tolovlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Qarz to'lovi",
                'verbose_name_plural': "Qarz to'lovlari",
            },
        ),
    ]
