# Generated by Django 6.0.7 on 2026-08-23 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0002_qarztolovi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarztolovi',
            name='qabul_qilgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qabul_qilingan_qarz_tolovlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='kim_yozgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yozgan_xarajatlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
