# Generated by Django 6.0.7 on 2026-08-03 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirishnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('yangi_buyurtma', 'Yangi buyurtma'), ('qarz', 'Qarz eslatmasi'), ('buyurtma_olindi', 'Buyurtma olindi'), ('yetkazildi', 'Yetkazildi'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20)),
                ('matn', models.CharField(max_length=255)),
                ('havola', models.CharField(blank=True, max_length=255, null=True)),
                ('oqilgan', models.BooleanField(default=False)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='BildirishnomaSozlamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yangi_buyurtma_eslatmasi', models.BooleanField(default=True)),
                ('qarz_eslatmasi', models.BooleanField(default=True)),
                ('eslatma_vaqti', models.TimeField(default='09:00')),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnoma_sozlamasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
