# Generated by Django 6.0.7 on 2026-08-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirishnomalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirishnomasozlamasi',
            name='xarajat_eslatmasi',
            field=models.BooleanField(default=True),
        ),
    ]
