# Generated by Django 6.0.7 on 2026-08-01 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokonlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('yetkazilmoqda', 'Yetkazilmoqda'), ('yetkazildi', 'Yetkazildi')], default='yangi', max_length=20)),
                ('tolov_holati', models.CharField(blank=True, choices=[('kutilmoqda', 'Kutilmoqda'), ('tolandi', "To'landi"), ('qarz', 'Qarz')], max_length=20, null=True)),
                ('qarz_summasi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yetkazilgan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('joylashuv_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('joylashuv_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dokon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtmalar', to='dokonlar.dokon')),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='menejer_buyurtmalari', to=settings.AUTH_USER_MODEL)),
                ('yetkazishga_olgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yetkazishga_olgan_buyurtmalar', to=settings.AUTH_USER_MODEL)),
                ('zakaz_olgan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakaz_olgan_buyurtmalar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyurtmaMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hajm', models.CharField(max_length=10)),
                ('soni_buyurtma_qilingan', models.IntegerField()),
                ('soni_yetkazilgan', models.IntegerField(blank=True, null=True)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='buyurtmalar.buyurtma')),
            ],
        ),
    ]
