# Generated by Django 6.0.7 on 2026-08-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyurtma',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='buyurtmamahsulot',
            options={'verbose_name': 'Buyurtma mahsuloti', 'verbose_name_plural': 'Buyurtma mahsulotlari'},
        ),
    ]
