# Generated by Django 6.0.7 on 2026-08-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmalar', '0002_alter_buyurtma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='asl_buyurtma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qoldiq_buyurtmalar', to='buyurtmalar.buyurtma', verbose_name='Qisman yetkazilgandan qolgan asl buyurtma'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='izoh',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
