# Generated by Django 6.0.7 on 2026-08-23 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmalar', '0003_buyurtma_asl_buyurtma_buyurtma_izoh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='zakaz_olgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zakaz_olgan_buyurtmalar', to=settings.AUTH_USER_MODEL),
        ),
    ]
