# Generated by Django 6.0.7 on 2026-08-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('manzili', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('joylashuv_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('joylashuv_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('menejer', models.ForeignKey(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dokonlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
