# Generated by Django 6.0.7 on 2026-08-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchilar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foydalanuvchi',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
