# Generated by Django 6.0.7 on 2026-08-06 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchilar', '0002_alter_foydalanuvchi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DastavchikRuxsatlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokon_tahrirlash', models.BooleanField(default=True, verbose_name="Do'konni tahrirlash")),
                ('dokon_ochirish', models.BooleanField(default=False, verbose_name="Do'konni o'chirish")),
                ('buyurtma_ochirish', models.BooleanField(default=True, verbose_name="O'zi yaratgan buyurtmani o'chirish")),
                ('ombor_korish', models.BooleanField(default=False, verbose_name="Ombor qoldig'ini ko'rish")),
                ('fura_boshqarish', models.BooleanField(default=False, verbose_name="Fura qo'shish/tahrirlash/o'chirish")),
                ('narxlarni_korish', models.BooleanField(default=False, verbose_name="Standart narxlarni ko'rish/o'zgartirish")),
                ('dastavchiklarni_korish', models.BooleanField(default=False, verbose_name="Boshqa dastavchiklar ro'yxatini ko'rish")),
                ('xarajat_qoshish', models.BooleanField(default=True, verbose_name="Xarajat qo'shish")),
                ('menejer', models.OneToOneField(limit_choices_to={'rol': 'menejer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dastavchik_ruxsatlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dastavchik ruxsati',
                'verbose_name_plural': 'Dastavchik ruxsatlari',
            },
        ),
    ]
