# Generated by Django 6.0.7 on 2026-08-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchilar', '0003_dastavchikruxsatlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='sessiya_muddati_kun',
            field=models.PositiveIntegerField(default=14, help_text='Necha kun login holatida qolish, 0 = brauzer yopilganda chiqadi', verbose_name='Sessiya muddati (kun)'),
        ),
    ]
